name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Install boost
    #   run: sudo add-apt-repository -y ppa:mhier/libboost-latest && sudo apt-get update && sudo apt-get install -y libboost1.70-dev && sudo apt-get install -y ninja-build

    - name: Install zeromq, libtool, PkgConfig and Ninja
      run: |
        sudo apt-get update && sudo apt-get install -y libtool pkg-config ninja
        git clone git://github.com/jedisct1/libsodium.git &&  cd libsodium && ./autogen.sh && ./configure --prefix /usr && make check -j$(nproc) && sudo make install && sudo ldconfig && cd ../
        git clone git://github.com/zeromq/libzmq.git && cd libzmq && ./autogen.sh && ./configure --prefix /usr && make -j$(nproc) && sudo make install && sudo ldconfig && cd ../
        git clone git://github.com/zeromq/zmqpp.git && cd zmqpp && make -j$(nproc) && sudo make sudo make PREFIX=/usr install && cd ..

    - name: Install docker.io
      run: |
        sudo apt-get install docker.io

    - name: run CMake
      run: cmake -G "Ninja" $GITHUB_WORKSPACE

    - name: Make all targets
      run: ninja

    - name: Run tests
      run: ctest -V
